"""Added titles to file

Revision ID: 47491edaeb40
Revises: 8eb9178f2896
Create Date: 2024-02-07 17:02:20.645308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47491edaeb40'
down_revision = '8eb9178f2896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
