"""added overdue bool

Revision ID: 6f0cb13e9669
Revises: 4cb8474c6d07
Create Date: 2024-02-09 17:07:30.555150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0cb13e9669'
down_revision = '4cb8474c6d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overdue', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_column('overdue')

    # ### end Alembic commands ###
