"""added duedate in assignment

Revision ID: 742dcad5ea9e
Revises: 47491edaeb40
Create Date: 2024-02-07 22:25:34.532556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742dcad5ea9e'
down_revision = '47491edaeb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duedate', sa.DateTime(), nullable=True),
    sa.Column('totalMarks', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_duedate'), ['duedate'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_user_id'), ['user_id'], unique=False)

    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_user_id'))
        batch_op.drop_index(batch_op.f('ix_submission_timestamp'))
        batch_op.drop_index(batch_op.f('ix_submission_file_id'))
        batch_op.drop_index(batch_op.f('ix_submission_assignment_id'))

    op.drop_table('submission')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_user_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_timestamp'))
        batch_op.drop_index(batch_op.f('ix_assignment_duedate'))

    op.drop_table('assignment')
    # ### end Alembic commands ###
