"""added role to users table

Revision ID: 76fdb430b0a0
Revises: c9c6bac88c35
Create Date: 2024-02-06 21:39:15.777009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fdb430b0a0'
down_revision = 'c9c6bac88c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
